version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=crud

  redis:
    image: redis:5.0.3
    restart: always
    command: redis-server /etc/redis/redis.conf
    ports:
      - "7005:6379"
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
      - ./data/redis:/data



