// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"context"
	"github.com/redis/go-redis/v9"
	"main/internal/campaign/repository"
	"main/pkg/db/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.Db, redis2 *redis.Client) *Service {
	repositoryRepository := repository.NewRepository(db)
	serviceService := NewService(repositoryRepository, redis2)
	return serviceService
}
