// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"context"
	"main/internal/campaign/repository"
	service2 "main/internal/campaign/service"
	repository2 "main/internal/targeting_rule/repository"
	service3 "main/internal/targeting_rule/service"
	"main/pkg/db/postgres"
	"main/pkg/redis"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster, redis2 *redis.Redis) *Service {
	repositoryRepository := repository.NewRepository(db)
	serviceService := service2.NewService(repositoryRepository, redis2)
	repository3 := repository2.NewRepository(db)
	service4 := service3.NewService(repository3, redis2)
	service5 := NewService(serviceService, service4)
	return service5
}
