// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package delivery

import (
	"context"
	"main/internal/campaign/repository"
	"main/internal/campaign/service"
	service3 "main/internal/delivery/service"
	repository2 "main/internal/targeting_rule/repository"
	service2 "main/internal/targeting_rule/service"
	"main/pkg/db/postgres"
	"main/pkg/redis"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster, redis2 *redis.Redis) *Controller {
	repositoryRepository := repository.NewRepository(db)
	serviceService := service.NewService(repositoryRepository, redis2)
	repository3 := repository2.NewRepository(db)
	service4 := service2.NewService(repository3, redis2)
	service5 := service3.NewService(serviceService, service4)
	controller := NewController(service5)
	return controller
}
