// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repository

import (
	"context"
	"main/pkg/db/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster) *Repository {
	repository := NewRepository(db)
	return repository
}
