// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package campaign

import (
	"context"
	"github.com/redis/go-redis/v9"
	"main/internal/campaign/repository"
	"main/internal/campaign/service"
	"main/pkg/db/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster, redis2 *redis.Client) *Controller {
	repositoryRepository := repository.NewRepository(db)
	serviceService := service.NewService(repositoryRepository, redis2)
	controller := NewController(serviceService)
	return controller
}
